### ISSUE TITLE
Create document to describe the passthrough process

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/elasticio.github.io#227] opened 2019-08-30 08:57 UTC
We still don't have a document describing the pass-through process. The old documentation page has a couple of articles but I presume we need something up-to-date.

The old pages: https://support.elastic.io/support/solutions/folders/14000114764

**Comment by drobiazko** [comment] 2019-08-30 09:04
Duplicate of #181

**Closed by drobiazko** 2019-08-30 09:04 UTC
Labels: how-to guides, missing information
